import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols

def carolina2(dataframe, set_col, male_col, female_col, replication_col, yvar_col):
    """
    Python implementation of North Carolina Design II analysis.
    """
    # 1. Input Validation: Check if columns exist
    req_cols = [set_col, male_col, female_col, replication_col, yvar_col]
    if not all(col in dataframe.columns for col in req_cols):
        raise ValueError("Error: One or more specified columns are not found in the dataframe.")
    
    # 2. Build a clean, internal dataframe
    # Categorical variables are cast to strings so statsmodels treats them as factors
    dat = pd.DataFrame({
        'set': dataframe[set_col].astype(str),
        'male': dataframe[male_col].astype(str),
        'female': dataframe[female_col].astype(str),
        'replication': dataframe[replication_col].astype(str),
        'y': pd.to_numeric(dataframe[yvar_col], errors='coerce')
    })
    
    # Drop rows with NaN in the response variable to match standard analysis behavior
    dat = dat.dropna(subset=['y'])
    
    # 3. Model Fitting
    # Note: R's nesting operator `a %in% b` is equivalent to the interaction `b:a`.
    # We use C() to explicitly tell statsmodels to treat these as categorical variables.
    formula_str = "y ~ C(set) + C(set):C(replication) + C(set):C(male) + C(set):C(female) + C(set):C(male):C(female)"
    model = ols(formula_str, data=dat).fit()
    
    # 4. Extract ANOVA and Summary Statistics
    # typ=1 specifies Type I Sequential Sum of Squares, which mimics R's default anova() behavior
    anva = sm.stats.anova_lm(model, typ=1)
    mean_y = dat['y'].mean()
    
    # Extract Mean Squares using the exact rownames generated by statsmodels
    try:
        ms_m  = anva.loc['C(set):C(male)', 'mean_sq']
        ms_f  = anva.loc['C(set):C(female)', 'mean_sq']
        ms_mf = anva.loc['C(set):C(male):C(female)', 'mean_sq']
        ms_e  = anva.loc['Residual', 'mean_sq']
    except KeyError as e:
        raise KeyError(f"Could not extract expected term from ANOVA table. Missing: {e}")
    
    # Calculate Coefficient of Variation (CV)
    cv_val = (np.sqrt(ms_e) / mean_y) * 100
    
    # Print Output
    print(f"North Carolina 2 Design Output: {yvar_col}\n")
    print(anva)
    print(f"\nCV: {cv_val:.2f}%\tMean: {mean_y:.4f}\n")
    
    # 5. Calculate Design Parameters (m, f, s, r)
    # .nunique() replicates R's nlevels() for extracting distinct count
    m = dat['male'].nunique()
    f = dat['female'].nunique()
    r = dat['replication'].nunique()
    s = dat['set'].nunique()  # Extracted to match original script, though unused in formulas below
    
    # 6. Calculate Variance Components (Corrected Denominators)
    var_m  = (ms_m - ms_mf) / (f * r)
    var_f  = (ms_f - ms_mf) / (m * r)
    var_mf = (ms_mf - ms_e) / r
    
    # Calculate Additive and Dominance Variances
    var_Am = 4 * var_m
    var_Af = 4 * var_f
    var_D  = 4 * var_mf
    
    # 7. Return Results as a Structured Dictionary
    output = {
        'model': model,
        'anova': anva,
        'cv': cv_val,
        'mean': mean_y,
        'var_m': var_m,
        'var_f': var_f,
        'var_mf': var_mf,
        'var_Am': var_Am,
        'var_Af': var_Af,
        'var_D': var_D
    }
    
    return output
