
carolina2_improved <- function(dataframe, set, male, female, replication, yvar) {
  
  # 1. Input Validation: Check if columns exist
  req_cols <- c(set, male, female, replication, yvar)
  if (!all(req_cols %in% names(dataframe))) {
    stop("Error: One or more specified columns are not found in the dataframe.")
  }
  
  # 2. Build a clean, internal dataframe
  # This avoids naming conflicts and ensures data types are correct immediately
  dat <- data.frame(
    set         = as.factor(dataframe[[set]]),
    male        = as.factor(dataframe[[male]]),
    female      = as.factor(dataframe[[female]]),
    replication = as.factor(dataframe[[replication]]),
    y           = as.numeric(dataframe[[yvar]])
  )
  
  # 3. Model Fitting
  # Using the standardized variable names from 'dat'
  formula_str <- "y ~ set + replication %in% set + male %in% set + female %in% set + male:female %in% set"
  model <- lm(as.formula(formula_str), data = dat)
  
  # 4. Extract ANOVA and Summary Statistics
  anva <- anova(model)
  mean_y <- mean(dat$y, na.rm = TRUE)
  
  # Extract Mean Squares safely using the exact rownames generated by lm()
  ms_m  <- anva["set:male", "Mean Sq"]
  ms_f  <- anva["set:female", "Mean Sq"]
  ms_mf <- anva["set:male:female", "Mean Sq"]
  ms_e  <- anva["Residuals", "Mean Sq"]
  
  # Simplify CV Calculation
  # The original custom cv.model function manually calculated the Residual Mean Square (MSE).
  # We can just use the MSE directly from the ANOVA table (ms_e).
  cv_val <- (sqrt(ms_e) / mean_y) * 100
  
  # Print Output
  cat("North Carolina 2 Design Output: ", yvar, "\n\n")
  print(anva)
  cat(sprintf("\nCV: %.2f%%\tMean: %.4f\n", cv_val, mean_y))
  
  # 5. Calculate Design Parameters (m, f, s, r)
  m <- nlevels(dat$male)
  f <- nlevels(dat$female)
  r <- nlevels(dat$replication)
  s <- nlevels(dat$set)
  
  # 6. Calculate Variance Components (Corrected Denominators)
  var_m  <- (ms_m - ms_mf) / (f * r)
  var_f  <- (ms_f - ms_mf) / (m * r)
  var_mf <- (ms_mf - ms_e) / r
  
  # Calculate Additive and Dominance Variances
  var_Am <- 4 * var_m
  var_Af <- 4 * var_f
  var_D  <- 4 * var_mf
  
  # 7. Return Results as a Structured List
  output <- list(
    model  = model, 
    anova  = anva,
    cv     = cv_val,
    mean   = mean_y,
    var.m  = var_m, 
    var.f  = var_f,
    var.mf = var_mf, 
    var.Am = var_Am, 
    var.Af = var_Af,
    var.D  = var_D
  )
  
  return(invisible(output))
}

 